baseURL = "http://www.dawnbreak.tech"
title = "dawnbreak.tech"
theme = "poison"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true


[pagination]
pagerSize = 6 

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"