baseURL = "https://jason-dawnbreaktech.github.io/dawnbreak.tech/"
title = "dawnbreak.tech"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true


[pagination]
pagerSize = 6 

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[params] 
faviconSVG = ""
favicon_32 = "imgs/favicon-32x32.png"
favicon_16 = "imgs/favicon-16x16.png"
author = "JC Alan"
description = "JC Alan's personal website"
keywords = "blog,developer,personal"
info = ["IT Systems Alchemist"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2024
colorScheme = "auto"
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/jason-dawnbreaktech/"


[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/JC_Alan___"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/jasoncocrehamjr/"

[[params.social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-2x"
weight = 5
url = "https://www.youtube.com/@JC-Alan"

## [[params.social]]
## name = "Medium"
## icon = "fa-brands fa-medium fa-2x"
## weight = 5
## url = "https://medium.com/@johndoe"

## [[params.social]]
## name = "RSS"
## icon = "fa-solid fa-rss fa-2x"
## weight = 6
## url = "https://myhugosite.com/index.xml"
## rel = "alternate"
## type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"
